name: .NET Core

on:
  push:
    branches: 
    - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    #- name: Test
      #run: dotnet test --no-restore --verbosity normal
    - name: List out directory contents
      run: |
          echo "Listing the contents of the GitHub workspace directory"
          ls ${{ github.workspace }}
          echo "Recursively listing all contents of the current directory"
          ls -R
          
    - name: Unit test
      run: dotnet test ./AnimalAdoption.Web.Portal.UnitTests/AnimalAdoption.Web.Portal.UnitTests.csproj
          
    #- uses: actions/checkout@v2
    #- run: mkdir -p path/to/artifact
    #- run: echo hello > path/to/artifact/world.txt
      
    - name: Upload artifact
    - uses: actions/upload-artifact@v2
      with:
        name: AnimalAdoptionWebPortal
        path: ./AnimalAdoption.Web.Portal/bin/Release/netcoreapp3.1/AnimalAdoption.Web.Portal.dll
