name: .NET Core

on:
  push:
    branches: 
      #- '**'
      [ master ]
  pull_request:
    branches: 
      #- '**'
      [ master ]

env:
      GitHubPackageFeedUrl: https://nuget.pkg.github.com/AzureSprint/index.json
      LogicProjectPath: ${{ github.WORKSPACE }}/AnimalAdoption.Common.Logic
      AZURE_WEBAPP_NAME: AzureSprintWebAppTest  # set this to your application's name
      VERSION: 1.0.0
      AZURE_WEBAPP_PACKAGE_PATH: '.'  # set this to the path to your web app project, defaults to the repository root

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # Authenticates packages to push to GPR
    - name: Setup .NET Core @ Latest
      uses: actions/setup-dotnet@v1
      with:
        source-url: ${{ env.GitHubPackageFeedUrl }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically creates a GITHUB_TOKEN secret to use in your workflow
      
    #- name: Setup .NET Core
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: 3.1.301
    
    - name: Install dependencies
      run: dotnet restore

    - name: Package up project
      #run: dotnet pack --configuration Release ${{ env.LogicProjectPath }}
      run: dotnet pack -o . -p:PackageVersion=${{ env.VERSION }}.${{ github.run_number }}
      
    - name: Add NuGet Source
      #run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -n github -u ${{ github.repository_owner }} -p ${{ secrets.PACKAGES_PAT }} --store-password-in-clear-text
      run: dotnet nuget add source https://nuget.pkg.github.com/AzureSprint/index.json -n github -u ${{ github.repository_owner }} -p ${{ secrets.PACKAGES_PAT }} --store-password-in-clear-text

    - name: Publish NuGet Package
      run: dotnet nuget push *.nupkg --source "github" --api-key ${{ secrets.PACKAGES_PAT }} --skip-duplicate
      
    #- name: Push package to GitHub registry
      #run: dotnet nuget push ${{ env.LogicProjectPath }}/**/*.nupkg --skip-duplicate

    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test AnimalAdoption.Web.Portal.UnitTests --no-restore --verbosity normal
      
    - name: Publish
      run: dotnet publish AnimalAdoption.Web.Portal -o AnimalAdoption.Web.Portal/published
      
    #- name: List out directory contents
    #  run: |
    #      echo "Listing the contents of the GitHub workspace directory"
    #      ls ${{ github.workspace }}
    #      echo "Recursively listing all contents of the current directory"
    #      ls -R

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: AnimalAdoptionWebPortal
        #path: ./AnimalAdoption.Web.Portal/bin/Release/netcoreapp3.1/AnimalAdoption.Web.Portal.dll
        path: ${{ github.workspace }}/AnimalAdoption.Web.Portal/published

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: AnimalAdoptionWebPortal
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.PUBLISH_CREDENTIALS_DEV }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
